// <auto-generated />
using System;
using GymFinder.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymFinder.Api.Migrations
{
    [DbContext(typeof(GymFinderDbContext))]
    [Migration("20260202045645_AddNotificationSystem")]
    partial class AddNotificationSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymFinder.Api.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hot"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Best Seller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sale"
                        },
                        new
                        {
                            Id = 4,
                            Name = "New"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Premium"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Limited"
                        });
                });

            modelBuilder.Entity("GymFinder.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("GymFinder.Api.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mass Gainer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Whey Protein"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pre-Workout"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Creatine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "BCAA"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Protein Bar"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("GymFinder.Api.Models.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "88 Láng Hạ, Đống Đa, Hà Nội",
                            Description = "Trung tâm thể hình và yoga cao cấp với trang thiết bị hiện đại.",
                            Image = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop",
                            Name = "California Fitness & Yoga",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Address = "51 Xuân Diệu, Tây Hồ, Hà Nội",
                            Description = "Phòng tập sang trọng với hồ bơi và các lớp học group-X đa dạng.",
                            Image = "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=1470&auto=format&fit=crop",
                            Name = "Elite Fitness Xuan Dieu",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Address = "226 Cầu Giấy, Hà Nội",
                            Description = "Không gian tập luyện rộng rãi, phù hợp cho mọi trình độ.",
                            Image = "https://images.unsplash.com/photo-1571902251103-d87382404ff4?q=80&w=1374&auto=format&fit=crop",
                            Name = "City Gym Cầu Giấy",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Address = "68 Ngõ 310 Nghi Tàm, Tây Hồ, Hà Nội",
                            Description = "Phòng tập phong cách cộng đồng với nhiều lớp học outdoors.",
                            Image = "https://images.unsplash.com/photo-1623874514711-4f3b2580dc2e?q=80&w=1470&auto=format&fit=crop",
                            Name = "The Fitness Village",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tầng 4, 31 Láng Hạ, Đống Đa, Hà Nội",
                            Description = "Chuyên về Functional Training và CrossFit chuyên sâu.",
                            Image = "https://images.unsplash.com/photo-1574680096145-d05b474e2155?q=80&w=1469&auto=format&fit=crop",
                            Name = "Sweat Factory",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 6,
                            Address = "Tầng 5, 71 Nguyễn Chí Thanh, Hà Nội",
                            Description = "Tiện nghi và chuyên nghiệp hàng đầu tại khu vực Đống Đa.",
                            Image = "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?q=80&w=1469&auto=format&fit=crop",
                            Name = "Nshape Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 7,
                            Address = "Số 1 Võ Thị Sáu, Hai Bà Trưng, Hà Nội",
                            Description = "Phòng tập bình dân nhưng đầy đủ trang thiết bị và không gian rộng.",
                            Image = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1470&auto=format&fit=crop",
                            Name = "Blue Gym Võ Thị Sáu",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 8,
                            Address = "Tầng 3, Tràng An Complex, Cầu Giấy, Hà Nội",
                            Description = "Phòng tập cao cấp với bể bơi bốn mùa trên cao.",
                            Image = "https://images.unsplash.com/photo-1590239068531-291124237f37?q=80&w=1470&auto=format&fit=crop",
                            Name = "Level Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 9,
                            Address = "Số 5 Ngõ 12 Đặng Thai Mai, Tây Hồ, Hà Nội",
                            Description = "Phong cách boutique cá tính, tập trung vào PT và nhóm nhỏ.",
                            Image = "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?q=80&w=1470&auto=format&fit=crop",
                            Name = "GymHaus Boutique Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 10,
                            Address = "Tầng 4, The Garden, Mễ Trì, Hà Nội",
                            Description = "Khu phức hợp tập luyện và thư giãn đẳng cấp khu vực Mỹ Đình.",
                            Image = "https://images.unsplash.com/photo-1534367507873-d2d7e24c798f?q=80&w=1470&auto=format&fit=crop",
                            Name = "Star Fitness The Garden",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 11,
                            Address = "458 Minh Khai, Hai Bà Trưng, Hà Nội",
                            Description = "Chi nhánh Riverside với thiết kế sang trọng và view đẹp.",
                            Image = "https://images.unsplash.com/photo-1550345332-09e3ac987658?q=80&w=1374&auto=format&fit=crop",
                            Name = "Cali Century Riverside",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 12,
                            Address = "25 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội",
                            Description = "Hoạt động 24/7, phù hợp cho những người bận rộn.",
                            Image = "https://images.unsplash.com/photo-1519501025264-65ba15a82390?q=80&w=1528&auto=format&fit=crop",
                            Name = "Gym 24 Seven",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 13,
                            Address = "Tầng 4-5, số 36A La Thành, Ô Chợ Dừa, Hà Nội",
                            Description = "Không gian tập luyện hiện đại với phong cách industrial cực chất.",
                            Image = "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=1470",
                            Name = "Teekiu Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 14,
                            Address = "Tầng 4, tháp C, Golden Palace, Mễ Trì, Hà Nội",
                            Description = "Tổ hợp chăm sóc sức khỏe 5 sao với bể bơi nước mặn.",
                            Image = "https://images.unsplash.com/photo-1571902251103-d87382404ff4?auto=format&fit=crop&q=80&w=1470",
                            Name = "Golden Wellness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 15,
                            Address = "Tầng 27, tháp Mipec, 229 Tây Sơn, Hà Nội",
                            Description = "View toàn thành phố từ tầng cao, máy móc chuẩn quốc tế.",
                            Image = "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?auto=format&fit=crop&q=80&w=1470",
                            Name = "Peak Fitness Hà Nội",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 16,
                            Address = "Số 1 Kim Mã, Ba Đình, Hà Nội",
                            Description = "Phòng tập yên tĩnh, chuyên sâu về Yoga trị liệu và thiền.",
                            Image = "https://images.unsplash.com/photo-1545208393-2160291ba86e?auto=format&fit=crop&q=80&w=1470",
                            Name = "Aura Fitness & Yoga",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 17,
                            Address = "Số 1 Phùng Hưng, Hà Đông, Hà Nội",
                            Description = "Hệ thống phòng tập giá rẻ nhưng chất lượng chuyên nghiệp.",
                            Image = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=1470",
                            Name = "Fit City Hà Đông",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 18,
                            Address = "Tầng 2, 101 Láng Hạ, Đống Đa, Hà Nội",
                            Description = "Phòng tập trẻ trung, cộng đồng tập luyện năng động.",
                            Image = "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=1470",
                            Name = "Fuel Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 19,
                            Address = "Số 9 Nguyễn Trãi, Thanh Xuân, Hà Nội",
                            Description = "Chuyên về Boxing, Muay Thai và võ thuật kết hợp thể hình.",
                            Image = "https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?auto=format&fit=crop&q=80&w=1470",
                            Name = "Kickfit Sports Nguyễn Trãi",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 20,
                            Address = "Tầng 4, 114 Mai Hắc Đế, Hai Bà Trưng, Hà Nội",
                            Description = "Thiết kế sang trọng, khu vực xông hơi và thư giãn tuyệt vời.",
                            Image = "https://images.unsplash.com/photo-1623874514711-4f3b2580dc2e?auto=format&fit=crop&q=80&w=1470",
                            Name = "Jade Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 21,
                            Address = "Ngõ 102 Ngụy Như Kon Tum, Thanh Xuân, Hà Nội",
                            Description = "Phòng tập private dành cho những ai thích sự riêng tư.",
                            Image = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=1470",
                            Name = "F5 Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 22,
                            Address = "Tầng 7, Keangnam Landmark 72, Nam Từ Liêm, Hà Nội",
                            Description = "Đẳng cấp thượng lưu với đầy đủ dịch vụ nghỉ dưỡng.",
                            Image = "https://images.unsplash.com/photo-1590239068531-291124237f37?auto=format&fit=crop&q=80&w=1470",
                            Name = "Landmark 72 Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 23,
                            Address = "Số 110 Hoàng Quốc Việt, Cầu Giấy, Hà Nội",
                            Description = "Lựa chọn tốt nhất cho các tín đồ đam mê Bodybuilding.",
                            Image = "https://images.unsplash.com/photo-1583454110551-21f2fa2021b1?auto=format&fit=crop&q=80&w=1470",
                            Name = "Rambo Gym",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 24,
                            Address = "Số 194 Thái Thịnh, Đống Đa, Hà Nội",
                            Description = "Phòng tập bình dân, không gian thoáng mát, giá sinh viên.",
                            Image = "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&q=80&w=1470",
                            Name = "MD Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 25,
                            Address = "Dịch Vọng Hậu, Cầu Giấy, Hà Nội",
                            Description = "Phòng tập hardcore cho nam giới với tạ nặng và đa dạng.",
                            Image = "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&q=80&w=1470",
                            Name = "X-Men Gym",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 26,
                            Address = "Tầng 3, Aeon Mall Long Biên, Hà Nội",
                            Description = "Trung tâm chuyên biệt về Yoga với giáo viên Ấn Độ.",
                            Image = "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?auto=format&fit=crop&q=80&w=1470",
                            Name = "Yoga Plus",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 27,
                            Address = "Khu đô thị Việt Hưng, Long Biên, Hà Nội",
                            Description = "Phòng tập hiện đại hàng đầu khu vực phía Đông Hà Nội.",
                            Image = "https://images.unsplash.com/photo-1534367507873-d2d7e24c798f?auto=format&fit=crop&q=80&w=1470",
                            Name = "Long Biên Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 28,
                            Address = "1/163 Hoàng Ngân, Trung Hòa, Cầu Giấy, Hà Nội",
                            Description = "Mô hình CLB gia đình sang trọng với bể bơi ngoài trời.",
                            Image = "https://images.unsplash.com/photo-1550345332-09e3ac987658?auto=format&fit=crop&q=80&w=1470",
                            Name = "Mfitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 29,
                            Address = "Tầng hầm B1, T6 Times City, Hà Nội",
                            Description = "Tiện lợi cho cư dân với hệ thống máy móc LifeFitness.",
                            Image = "https://images.unsplash.com/photo-1596357399117-574246604163?auto=format&fit=crop&q=80&w=1470",
                            Name = "Times City Gym",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 30,
                            Address = "101 Xuân La, Tây Hồ, Hà Nội",
                            Description = "Tận hưởng không gian tập luyện chuyên nghiệp gần Hồ Tây.",
                            Image = "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&q=80&w=1470",
                            Name = "Passion Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 31,
                            Address = "Ngõ 376 Bưởi, Ba Đình, Hà Nội",
                            Description = "Chất lượng cao, giá thành hợp lý, cộng đồng thân thiện.",
                            Image = "https://images.unsplash.com/photo-1517130038641-a774d04afb3c?auto=format&fit=crop&q=80&w=1470",
                            Name = "Topgym Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 32,
                            Address = "Tòa nhà Hồ Gươm Plaza, Hà Đông, Hà Nội",
                            Description = "Tiêu chuẩn Châu Âu ngay tại cửa ngõ phía Tây.",
                            Image = "https://images.unsplash.com/photo-1599058917233-3583e717c06c?auto=format&fit=crop&q=80&w=1470",
                            Name = "Fit24 Hà Đông",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 33,
                            Address = "Hào Nam, Đống Đa, Hà Nội",
                            Description = "Sự kết hợp hoàn hảo giữa tập luyện và dinh dưỡng.",
                            Image = "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&q=80&w=1470",
                            Name = "Lofit",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 34,
                            Address = "Văn Quán, Hà Đông, Hà Nội",
                            Description = "Lò luyện sức mạnh với các bài tập Compound kinh điển.",
                            Image = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=1470",
                            Name = "Strong First",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 35,
                            Address = "HH Linh Đàm, Hoàng Mai, Hà Nội",
                            Description = "Phòng tập đông vui, nhộn nhịp tại khu vực Linh Đàm.",
                            Image = "https://images.unsplash.com/photo-1591117207239-788bf8de6c3b?auto=format&fit=crop&q=80&w=1470",
                            Name = "The Gym Linh Đàm",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 36,
                            Address = "Phan Chu Trinh, Hoàn Kiếm, Hà Nội",
                            Description = "Trải nghiệm tập luyện như tại nhà với PT cá nhân.",
                            Image = "https://images.unsplash.com/photo-1584735935682-2f2b69dff3d2?auto=format&fit=crop&q=80&w=1470",
                            Name = "Wefit Home",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 37,
                            Address = "Tố Hữu, Nam Từ Liêm, Hà Nội",
                            Description = "Hệ thống máy tập Cardio đa dạng giúp giảm cân hiệu quả.",
                            Image = "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=1470",
                            Name = "Unifit Hà Nội",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 38,
                            Address = "Tòa nhà CT2, Mỹ Đình 2, Nam Từ Liêm, Hà Nội",
                            Description = "Phòng tập sạch sẽ, máy móc được bảo trì liên tục.",
                            Image = "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?auto=format&fit=crop&q=80&w=1470",
                            Name = "The Light Fitness",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 39,
                            Address = "Kim Giang, Hoàng Mai, Hà Nội",
                            Description = "Địa điểm tập luyện lý tưởng cho các bạn học sinh sinh viên.",
                            Image = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=1470",
                            Name = "Gym King",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 40,
                            Address = "Lê Đức Thọ, Nam Từ Liêm, Hà Nội",
                            Description = "Chuyên về đào tạo vận động viên thi đấu thể hình.",
                            Image = "https://images.unsplash.com/photo-1581009146145-b5ef03a74e7f?auto=format&fit=crop&q=80&w=1470",
                            Name = "Ares Gym",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 41,
                            Address = "Phạm Văn Đồng, Bắc Từ Liêm, Hà Nội",
                            Description = "Rộng rãi, nhiều lớp Group-X thú vị như Zumba, Sexy Dance.",
                            Image = "https://images.unsplash.com/photo-1522898467493-49d5f8f5db14?auto=format&fit=crop&q=80&w=1470",
                            Name = "Victory Fitness",
                            OwnerId = 1,
                            PricePerHour = 60000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 42,
                            Address = "KĐT Định Công, Hoàng Mai, Hà Nội",
                            Description = "Thiết kế mở, gần gũi thiên nhiên, tập luyện thư thái.",
                            Image = "https://images.unsplash.com/photo-1544033527-b192daee1f5b?auto=format&fit=crop&q=80&w=1470",
                            Name = "The Garden Gym",
                            OwnerId = 1,
                            PricePerHour = 50000m,
                            Rating = 4.2999999999999998
                        });
                });

            modelBuilder.Entity("GymFinder.Api.Models.GymReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId");

                    b.ToTable("GymReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 2, 4, 56, 45, 311, DateTimeKind.Utc).AddTicks(7986),
                            GymId = 1,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 2, 4, 56, 45, 311, DateTimeKind.Utc).AddTicks(8287),
                            GymId = 1,
                            Rating = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GymFinder.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GymFinder.Api.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("HoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GymId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2023/12/15/resized/serious-mass-12lbs_1702628517.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2023/12/15/resized/serious-mass-12lbs_1702628517.jpg.webp",
                            Name = "ON Serious Mass",
                            OriginalPrice = 1300000m,
                            Price = 1100000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2023/12/19/resized/mass-tech-extreme-2000-22lbs_1702956244.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2023/12/19/resized/mass-tech-extreme-2000-22lbs_1702956244.jpg.webp",
                            Name = "Mass Tech Extreme 2000",
                            OriginalPrice = 1800000m,
                            Price = 1550000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/12/07/resized/mutant-mass-15lbs_1733541654.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2024/12/07/resized/mutant-mass-15lbs_1733541654.jpg.webp",
                            Name = "Mutant Mass 15lbs",
                            OriginalPrice = 1950000m,
                            Price = 1630000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2023/11/23/large/platinum-hydro-whey-3-5lbs_1700708519.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2023/11/23/large/platinum-hydro-whey-3-5lbs_1700708519.jpg.webp",
                            Name = "ON Platinum Hydro Whey 3.5lbs",
                            OriginalPrice = 2900000m,
                            Price = 2550000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2023/12/14/resized/muscle-mass-gainer-12lbs_1702547889.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2023/12/14/resized/muscle-mass-gainer-12lbs_1702547889.jpg.webp",
                            Name = "Labrada Muscle Mass Gainer",
                            Price = 1550000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2023/12/15/large/mass-fusion-12lbs_1702610773.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2023/12/15/large/mass-fusion-12lbs_1702610773.jpg.webp",
                            Name = "Nutrabolics Mass Fusion 12lbs",
                            OriginalPrice = 1850000m,
                            Price = 1690000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2025/10/31/large/beverly-hydrolyzed-whey-delicatesse-2-2lbs_1761880514.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2025/10/31/large/beverly-hydrolyzed-whey-delicatesse-2-2lbs_1761880514.jpg.webp",
                            Name = "Beverly Hydrolyzed Whey Delicatesse",
                            OriginalPrice = 1500000m,
                            Price = 1350000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2026/01/08/large/rule-1-protein-1-98lbs_1767854498.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2026/01/08/large/rule-1-protein-1-98lbs_1767854498.jpg.webp",
                            Name = "Rule1 Protein 1.98lbs",
                            OriginalPrice = 1650000m,
                            Price = 1450000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2025/06/25/large/bpi-iso-hd-5lbs_1750826723.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2025/06/25/large/bpi-iso-hd-5lbs_1750826723.jpg.webp",
                            Name = "BPI ISO HD 100% Pure Isolate",
                            Price = 1850000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/02/05/large/12-banh-critical-cookie_1707123280.jpg.webp",
                            Image = "https://www.wheystore.vn/images/products/2024/02/05/large/12-banh-critical-cookie_1707123280.jpg.webp",
                            Name = "Applied Nutrition Critical Cookie 12 x",
                            Price = 740000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/01/18/resized/binh-lac-wheystore-1-ngan_1705572623.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/01/18/resized/binh-lac-wheystore-1-ngan_1705572623.jpg",
                            Name = "Bình lắc WheyStore 1 ngăn - 600ml",
                            Price = 150000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/01/19/resized/binh-lac-amix-nutrition-600ml_1705651699.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/01/19/resized/binh-lac-amix-nutrition-600ml_1705651699.jpg",
                            Name = "Bình lắc Amix Nutrition 2 ngăn",
                            Price = 180000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/02/01/resized/binh-lac-perfect-nutrition-900ml_1706753309.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/02/01/resized/binh-lac-perfect-nutrition-900ml_1706753309.jpg",
                            Name = "Bình lắc Perfect Nutrition",
                            Price = 190000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/01/19/resized/binh-lac-ronnie-coleman_1705656016.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/01/19/resized/binh-lac-ronnie-coleman_1705656016.jpg",
                            Name = "SmartShake Ronnie Coleman 3 ngăn",
                            Price = 250000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/01/19/resized/bao-tay-wheystore_1705649952.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/01/19/resized/bao-tay-wheystore_1705649952.jpg",
                            Name = "Bao tay WheyStore (Gym Gloves)",
                            OriginalPrice = 220000m,
                            Price = 180000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/01/19/resized/quan-co-tay-wheystore_1705649918.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/01/19/resized/quan-co-tay-wheystore_1705649918.jpg",
                            Name = "Quấn Cổ Tay WheyStore",
                            Price = 150000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/01/19/resized/dai-moc-cap-tap-chan-wheystore_1705654258.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/01/19/resized/dai-moc-cap-tap-chan-wheystore_1705654258.jpg",
                            Name = "Đai móc cáp tập chân WheyStore",
                            Price = 150000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            GymId = 1,
                            HoverImage = "https://www.wheystore.vn/images/products/2024/01/22/resized/day-keo-lifting-strap-wheystore_1705908393.jpg",
                            Image = "https://www.wheystore.vn/images/products/2024/01/22/resized/day-keo-lifting-strap-wheystore_1705908393.jpg",
                            Name = "Dây kéo lưng Lifting Strap",
                            Price = 150000m,
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("GymFinder.Api.Models.ProductBadge", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("ProductBadges");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BadgeId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            BadgeId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            BadgeId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            BadgeId = 4
                        },
                        new
                        {
                            ProductId = 7,
                            BadgeId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            BadgeId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            BadgeId = 4
                        },
                        new
                        {
                            ProductId = 13,
                            BadgeId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            BadgeId = 6
                        },
                        new
                        {
                            ProductId = 18,
                            BadgeId = 2
                        });
                });

            modelBuilder.Entity("GymFinder.Api.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("GymFinder.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gym.com",
                            FullName = "Admin User",
                            PasswordHash = "hash",
                            Role = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Email = "a@gym.com",
                            FullName = "Nguyen Van A",
                            PasswordHash = "hash",
                            Role = "USER"
                        },
                        new
                        {
                            Id = 3,
                            Email = "b@gym.com",
                            FullName = "Tran Thi B",
                            PasswordHash = "hash",
                            Role = "USER"
                        },
                        new
                        {
                            Id = 4,
                            Email = "c@gym.com",
                            FullName = "Le Van C",
                            PasswordHash = "hash",
                            Role = "USER"
                        },
                        new
                        {
                            Id = 5,
                            Email = "d@gym.com",
                            FullName = "Pham Minh D",
                            PasswordHash = "hash",
                            Role = "USER"
                        });
                });

            modelBuilder.Entity("GymFinder.Api.Models.Booking", b =>
                {
                    b.HasOne("GymFinder.Api.Models.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinder.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Cart", b =>
                {
                    b.HasOne("GymFinder.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("GymFinder.Api.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFinder.Api.Models.CartItem", b =>
                {
                    b.HasOne("GymFinder.Api.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinder.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Gym", b =>
                {
                    b.HasOne("GymFinder.Api.Models.User", "Owner")
                        .WithMany("OwnedGyms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GymFinder.Api.Models.GymReview", b =>
                {
                    b.HasOne("GymFinder.Api.Models.Gym", "Gym")
                        .WithMany("Reviews")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinder.Api.Models.User", "User")
                        .WithMany("GymReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Notification", b =>
                {
                    b.HasOne("GymFinder.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Order", b =>
                {
                    b.HasOne("GymFinder.Api.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymFinder.Api.Models.OrderDetail", b =>
                {
                    b.HasOne("GymFinder.Api.Models.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinder.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Product", b =>
                {
                    b.HasOne("GymFinder.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinder.Api.Models.Gym", "Gym")
                        .WithMany("Products")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymFinder.Api.Models.ProductBadge", b =>
                {
                    b.HasOne("GymFinder.Api.Models.Badge", "Badge")
                        .WithMany("ProductBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinder.Api.Models.Product", "Product")
                        .WithMany("ProductBadges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymFinder.Api.Models.ProductReview", b =>
                {
                    b.HasOne("GymFinder.Api.Models.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFinder.Api.Models.User", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Badge", b =>
                {
                    b.Navigation("ProductBadges");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Gym", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("GymFinder.Api.Models.Product", b =>
                {
                    b.Navigation("ProductBadges");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("GymFinder.Api.Models.User", b =>
                {
                    b.Navigation("GymReviews");

                    b.Navigation("Orders");

                    b.Navigation("OwnedGyms");

                    b.Navigation("ProductReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
